num = int(input('Digite um numero: '))
print('A TABUADA DE {}'.format(num))
print('0 * {} = {}.'.format(num, 0*num))
print('1 * {} = {}.'.format(num, 1*num))
print('2 * {} = {}.'.format(num, 2*num))
print('3 * {} = {}.'.format(num, 3*num))
print('4 * {} = {}.'.format(num, 4*num))
print('5 * {} = {}.'.format(num, 5*num))
print('6 * {} = {}.'.format(num, 6*num))
print('7 * {} = {}.'.format(num, 7*num))
print('8 * {} = {}.'.format(num, 8*num))
print('9 * {} = {}.'.format(num, 9*num))
print('10 * {} = {}.'.format(num, 10*num))